# Generated by Django 3.2.9 on 2021-11-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('displayPicture', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=20)),
                ('personalStatement', models.CharField(max_length=500)),
                ('hairColor', models.CharField(max_length=20)),
                ('eyeColor', models.CharField(max_length=20)),
                ('accents', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=200)),
                ('playAgeMin', models.IntegerField(default=25)),
                ('playAgeMax', models.IntegerField(default=35)),
                ('links', models.CharField(max_length=500)),
                ('education', models.CharField(max_length=500)),
            ],
        ),
    ]
