# Generated by Django 3.2.9 on 2021-11-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20211122_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='gender',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiles',
            name='personalStatement',
            field=models.CharField(max_length=1000),
        ),
    ]
