# Generated by Django 3.2.9 on 2021-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20211123_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
