# Generated by Django 3.2.9 on 2021-11-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profiles_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='gender',
        ),
    ]
