# Generated by Django 3.2.9 on 2021-11-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profiles_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='gender',
            field=models.CharField(default='unspecified', max_length=20),
            preserve_default=False,
        ),
    ]
